set(package_tools
  AccurateMassSearch
  AssayGeneratorMetabo
  AssayGeneratorMetaboSirius
  BaselineFilter
  CVInspector
  ClusterMassTraces
  ClusterMassTracesByPrecursor
  CometAdapter
  ConsensusID
  ConsensusMapNormalizer
  DTAExtractor
  DatabaseFilter
  DatabaseSuitability
  DeMeanderize
  Decharger
  DecoyDatabase
  Digestor
  DigestorMotif
  EICExtractor
  Epifany
  ExternalCalibration
  FalseDiscoveryRate
  FeatureFinderCentroided
  FeatureFinderIdentification
  FeatureFinderLFQ
  FeatureFinderMetabo
  FeatureFinderMetaboIdent
  FeatureFinderMultiplex
  FeatureLinkerLabeled
  FeatureLinkerUnlabeled
  FeatureLinkerUnlabeledKD
  FeatureLinkerUnlabeledQT
  FeatureLinkerWNet
  FileConverter
  FileFilter
  FileInfo
  FileMerger
  FuzzyDiff
  GNPSExport
  HighResPrecursorMassCorrector
  IDConflictResolver
  IDDecoyProbability
  IDExtractor
  IDFileConverter
  IDFilter
  IDMapper
  IDMerger
  IDPosteriorErrorProbability
  IDRTCalibration
  IDRipper
  IDScoreSwitcher
  IDSplitter
  INIUpdater
  InternalCalibration
  IonMobilityBinning
  IsobaricAnalyzer
  IsobaricWorkflow
  JSONExporter
  LuciphorAdapter
  MRMMapper
  MRMPairFinder
  MSFraggerAdapter
  MSGFPlusAdapter
  MSstatsConverter
  MaRaClusterAdapter
  MapAlignerIdentification
  MapAlignerPoseClustering
  MapAlignerTreeGuided
  MapNormalizer
  MapRTTransformer
  MapStatistics
  MascotAdapterOnline
  MassCalculator
  MassTraceExtractor
  MetaProSIP
  MetaboliteAdductDecharger
  MetaboliteSpectralMatcher
  MultiplexResolver
  MzMLSplitter
  MzTabExporter
  NoiseFilterGaussian
  NoiseFilterSGolay
  NovorAdapter
  NucleicAcidSearchEngine
  OpenMSDatabasesInfo
  OpenMSInfo
  OpenNuXL
  OpenPepXL
  PSMFeatureExtractor
  ParquetConverter
  ParquetDiff
  PeakPickerHiRes
  PeakPickerIM
  PeakPickerIterative
  PeptideIndexer
  PercolatorAdapter
  PhosphoScoring
  ProSE
  ProteinInference
  ProteinQuantifier
  ProteomicsLFQ
  QCCalculator
  QCEmbedder
  QCExporter
  QCExtractor
  QCImporter
  QCMerger
  QCShrinker
  QualityControl
  RNADigestor
  RNAMassCalculator
  RNPxlXICFilter
  Resampler
  SageAdapter
  SeedListGenerator
  SemanticValidator
  SequenceCoverageCalculator
  SimpleSearchEngine
  SiriusExport
  SpectraFilterNLargest
  SpectraFilterNormalizer
  SpectraFilterThresholdMower
  SpectraFilterWindowMower
  SpectraMerger
  SpectraSTSearchAdapter
  StaticModification
  TICCalculator
  TextExporter
  UniPEFF
  XFDR
  XMLValidator
)
