# SPDX-License-Identifier: BSD-3-Clause
# Canonical source: OpenMS4-tests/cmake; generated standalone package copies.
include_guard(GLOBAL)

# tools.json owns registration and metadata. ARGN lists textually included helpers.
function(openms4_load_tools output)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/tools.json")
  file(READ "${PROJECT_SOURCE_DIR}/tools.json" _metadata)
  string(JSON _count LENGTH "${_metadata}" tools)
  if(_count EQUAL 0)
    message(FATAL_ERROR "Tool metadata must contain at least one executable")
  endif()
  math(EXPR _last "${_count} - 1")
  set(_all_names)
  set(_enabled)
  foreach(_index RANGE ${_last})
    string(JSON _name GET "${_metadata}" tools ${_index} name)
    string(JSON _category GET "${_metadata}" tools ${_index} category)
    if(NOT _name MATCHES "^[A-Za-z][A-Za-z0-9_]*$" OR _name IN_LIST _all_names
        OR _category STREQUAL "" OR _category MATCHES "[\t\r\n;]")
      message(FATAL_ERROR "Invalid or duplicate tool metadata: ${_name}")
    endif()
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/src/${_name}.cpp")
      message(FATAL_ERROR "Tool metadata has no source: ${_name}")
    endif()
    list(APPEND _all_names "${_name}")
    string(JSON _feature ERROR_VARIABLE _no_feature GET "${_metadata}" tools ${_index} requires_feature)
    if(NOT _no_feature)
      if(NOT _feature MATCHES "^OpenMS_WITH_[A-Z0-9_]+$" OR NOT DEFINED ${_feature})
        message(FATAL_ERROR "Unknown SDK feature for ${_name}: ${_feature}")
      endif()
      if(NOT ${_feature})
        continue()
      endif()
    endif()
    list(APPEND _enabled "${_name}")
    set(${_name}_CATEGORY "${_category}" PARENT_SCOPE)
  endforeach()
  file(GLOB _sources CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/*.cpp")
  foreach(_source IN LISTS _sources)
    get_filename_component(_name "${_source}" NAME_WE)
    if(NOT _name IN_LIST _all_names AND NOT _name IN_LIST ARGN)
      message(FATAL_ERROR "Tool source is missing metadata: ${_name}")
    endif()
  endforeach()
  set(${output} "${_enabled}" PARENT_SCOPE)
endfunction()

# Register already-created tools; each package keeps ownership of its targets and
# backend linkage. The build bindir can differ from GNUInstallDirs (notably NuXL).
function(openms4_install_tools package build_bindir)
  if(BUILD_TESTING)
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
  endif()
  set(manifest "# name\tcategory\tversion\texecutable\n")
  set(build_manifest "${manifest}")
  foreach(tool IN LISTS ARGN)
    target_compile_features(${tool} PRIVATE cxx_std_23)
    openms4_install_rpath(${tool})
    install(TARGETS ${tool} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
    string(APPEND manifest "${tool}\t${${tool}_CATEGORY}\t${PROJECT_VERSION}\t${CMAKE_INSTALL_BINDIR}/${tool}${CMAKE_EXECUTABLE_SUFFIX}\n")
    string(APPEND build_manifest "${tool}\t${${tool}_CATEGORY}\t${PROJECT_VERSION}\t${build_bindir}/${tool}${CMAKE_EXECUTABLE_SUFFIX}\n")
    if(BUILD_TESTING AND NOT tool STREQUAL "OpenMSInfo")
      foreach(kind ini ctd)
        add_test(NAME ${tool}_write_${kind} COMMAND ${Python3_EXECUTABLE}
          ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/CheckToolMetadata.py $<TARGET_FILE:${tool}>
          ${tool} ${PROJECT_VERSION} "${${tool}_CATEGORY}" ${kind}
          ${CMAKE_CURRENT_BINARY_DIR}/metadata/${kind}/${tool}.${kind})
        set_tests_properties(${tool}_write_${kind} PROPERTIES ENVIRONMENT
          "OPENMS_TOOL_PREFIX_PATH=${CMAKE_BINARY_DIR};OPENMS_DISABLE_UPDATE_CHECK=ON")
      endforeach()
    endif()
  endforeach()
  file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/share/openms4/tools ${CMAKE_BINARY_DIR}/install-manifests)
  file(WRITE ${CMAKE_BINARY_DIR}/share/openms4/tools/${package}.tools.tsv "${build_manifest}")
  file(WRITE ${CMAKE_BINARY_DIR}/install-manifests/${package}.tools.tsv "${manifest}")
  install(FILES ${CMAKE_BINARY_DIR}/install-manifests/${package}.tools.tsv DESTINATION share/openms4/tools)
endfunction()
