# SPDX-License-Identifier: BSD-3-Clause
# A package consumes installed, immutable SDKs; the suite never adds core sources.
include_guard(GLOBAL)
function(openms4_find_package name)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  file(READ "${_lock_file}" _lock)
  string(JSON _version ERROR_VARIABLE _err GET "${_lock}" dependencies "${name}" version)
  if(_err)
    message(FATAL_ERROR "No dependency lock for ${name}: ${_err}")
  endif()
  string(JSON _revision GET "${_lock}" dependencies "${name}" source_revision)
  if(NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "${name} source pin is not resolved")
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40)
    message(FATAL_ERROR "${name} requires a full 40-character Git revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(${name} ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT "${${name}_SOURCE_REVISION}" STREQUAL "${_revision}")
    message(FATAL_ERROR "${name} SDK revision mismatch: expected ${_revision}, got ${${name}_SOURCE_REVISION}")
  endif()
  # Propagate SDK metadata; imported targets already belong to this directory.
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^${name}_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_find_core)
  openms4_find_package(OpenMS ${ARGN})
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_source_revision output)
  # Child project() calls must not change the owning package identity.
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    get_filename_component(_package_root "${OPENMS4_DEPENDENCY_LOCK_FILE}" DIRECTORY)
  else()
    set(_package_root "${PROJECT_SOURCE_DIR}")
  endif()
  if(OPENMS4_SOURCE_REVISION)
    set(_revision "${OPENMS4_SOURCE_REVISION}")
  elseif(EXISTS "${_package_root}/.git")
    find_package(Git REQUIRED)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
      WORKING_DIRECTORY "${_package_root}"
      OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine package Git revision; set OPENMS4_SOURCE_REVISION explicitly")
    endif()
  else()
    message(FATAL_ERROR "Source archives must set OPENMS4_SOURCE_REVISION to their package commit")
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OPENMS4_SOURCE_REVISION must be the full 40-character lowercase package commit")
  endif()
  set(${output} "${_revision}" PARENT_SCOPE)
endfunction()

# Find only immutable data/feature metadata; suitable for LANGUAGES NONE projects.
function(openms4_find_core_data)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  file(READ "${_lock_file}" _lock)
  string(JSON _version GET "${_lock}" dependencies OpenMS version)
  string(JSON _revision GET "${_lock}" dependencies OpenMS source_revision)
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OpenMS requires a resolved 40-character source revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(OpenMSData ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT OpenMSData_SOURCE_REVISION STREQUAL _revision)
    message(FATAL_ERROR "OpenMS data revision mismatch: expected ${_revision}, got ${OpenMSData_SOURCE_REVISION}")
  endif()
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
