# SPDX-License-Identifier: BSD-3-Clause
# A package consumes installed, immutable SDKs; the suite never adds core sources.
# Canonical source: OpenMS4-tests/cmake; sync copies with tools/sync_build_helpers.py.
include_guard(GLOBAL)
# Every package's CI passes -DOPENMS4_WARNINGS_AS_ERRORS=ON, but only TOPP and FLASHTnT defined it,
# so CMake reported it as unused everywhere else and those warnings stayed warnings. Defining it here
# makes it mean the same in every package: the compiler's own default warnings become errors. TOPP and
# FLASHTnT additionally raise the warning level for their own targets (-Wall -Wextra, MSVC /W4).
option(OPENMS4_WARNINGS_AS_ERRORS "Treat package compiler warnings as errors" OFF)
set(CMAKE_COMPILE_WARNING_AS_ERROR ${OPENMS4_WARNINGS_AS_ERRORS})
option(OPENMS4_REQUIRE_CLEAN_SOURCE "Reject uncommitted package sources in published builds" OFF)
function(_openms4_dirty_value value label output)
  string(TOUPPER "${value}" _value)
  if(NOT _value MATCHES "^(ON|OFF|TRUE|FALSE|0|1)$")
    message(FATAL_ERROR "${label} must explicitly be ON or OFF")
  endif()
  if(_value)
    set(${output} ON PARENT_SCOPE)
  else()
    set(${output} OFF PARENT_SCOPE)
  endif()
endfunction()

function(_openms4_require_clean_sdk name)
  if(OPENMS4_REQUIRE_CLEAN_SOURCE)
    _openms4_dirty_value("${${name}_SOURCE_DIRTY}" "${name}_SOURCE_DIRTY" _dirty)
    if(_dirty)
      message(FATAL_ERROR "${name} SDK was built from uncommitted sources")
    endif()
  endif()
endfunction()

# Deferred until targets exist, so even a targeted build checks before compilation.
function(_openms4_attach_source_guard)
  get_property(_guard DIRECTORY PROPERTY OPENMS4_SOURCE_GUARD)
  get_property(_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  foreach(_target IN LISTS _targets)
    get_target_property(_type "${_target}" TYPE)
    if(_type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY)$")
      add_dependencies("${_target}" "${_guard}")
    endif()
  endforeach()
endfunction()

function(openms4_find_package name)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_lock_file}")
  file(READ "${_lock_file}" _lock)
  string(JSON _version ERROR_VARIABLE _err GET "${_lock}" dependencies "${name}" version)
  if(_err)
    message(FATAL_ERROR "No dependency lock for ${name}: ${_err}")
  endif()
  string(JSON _revision GET "${_lock}" dependencies "${name}" source_revision)
  if(NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "${name} source pin is not resolved")
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40)
    message(FATAL_ERROR "${name} requires a full 40-character Git revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(${name} ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT "${${name}_SOURCE_REVISION}" STREQUAL "${_revision}")
    message(FATAL_ERROR "${name} SDK revision mismatch: expected ${_revision}, got ${${name}_SOURCE_REVISION}")
  endif()
  _openms4_require_clean_sdk("${name}")
  openms4_source_revision(_package_revision _package_dirty)
  # Propagate SDK metadata; imported targets already belong to this directory.
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^${name}_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_find_core)
  openms4_find_package(OpenMS ${ARGN})
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
function(openms4_source_revision output)
  # Child project() calls must not change the owning package identity.
  if(OPENMS4_CHECK_SOURCE_DIR)
    set(_package_root "${OPENMS4_CHECK_SOURCE_DIR}")
  elseif(OPENMS4_DEPENDENCY_LOCK_FILE)
    get_filename_component(_package_root "${OPENMS4_DEPENDENCY_LOCK_FILE}" DIRECTORY)
  else()
    set(_package_root "${PROJECT_SOURCE_DIR}")
  endif()
  if(EXISTS "${_package_root}/.git")
    find_package(Git REQUIRED)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
      WORKING_DIRECTORY "${_package_root}"
      OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine package Git revision; set OPENMS4_SOURCE_REVISION explicitly")
    endif()
    if(OPENMS4_SOURCE_REVISION AND NOT OPENMS4_SOURCE_REVISION STREQUAL _revision)
      message(FATAL_ERROR "Source revision override differs from the package Git HEAD")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=all
      WORKING_DIRECTORY "${_package_root}" OUTPUT_VARIABLE _changes RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine uncommitted source changes")
    endif()
    set(_dirty OFF)
    if(NOT _changes STREQUAL "")
      set(_dirty ON)
    endif()
  else()
    if(NOT OPENMS4_SOURCE_REVISION OR NOT DEFINED OPENMS4_SOURCE_DIRTY)
      message(FATAL_ERROR "Source archives must set OPENMS4_SOURCE_REVISION and OPENMS4_SOURCE_DIRTY explicitly")
    endif()
    set(_revision "${OPENMS4_SOURCE_REVISION}")
    _openms4_dirty_value("${OPENMS4_SOURCE_DIRTY}" "OPENMS4_SOURCE_DIRTY" _dirty)
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OPENMS4_SOURCE_REVISION must be the full 40-character lowercase package commit")
  endif()
  if(OPENMS4_REQUIRE_CLEAN_SOURCE AND _dirty)
    message(FATAL_ERROR "Published packages require clean sources")
  endif()
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set(_guard "${PROJECT_NAME}_source_identity")
    if(NOT TARGET "${_guard}")
      add_custom_target("${_guard}" ALL
        COMMAND "${CMAKE_COMMAND}" "-DOPENMS4_CHECK_SOURCE_DIR=${_package_root}"
          "-DOPENMS4_SOURCE_REVISION=${_revision}" "-DOPENMS4_SOURCE_DIRTY=${_dirty}"
          "-DOPENMS4_EXPECTED_REVISION=${_revision}" "-DOPENMS4_EXPECTED_DIRTY=${_dirty}"
          "-DOPENMS4_REQUIRE_CLEAN_SOURCE=${OPENMS4_REQUIRE_CLEAN_SOURCE}"
          -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        VERBATIM)
      set_property(DIRECTORY PROPERTY OPENMS4_SOURCE_GUARD "${_guard}")
      cmake_language(DEFER CALL _openms4_attach_source_guard)
    endif()
  endif()
  set(${output} "${_revision}" PARENT_SCOPE)
  if(ARGC GREATER 1)
    set(${ARGV1} "${_dirty}" PARENT_SCOPE)
  endif()
endfunction()

# Find only immutable data/feature metadata; suitable for LANGUAGES NONE projects.
function(openms4_find_core_data)
  if(OPENMS4_DEPENDENCY_LOCK_FILE)
    set(_lock_file "${OPENMS4_DEPENDENCY_LOCK_FILE}")
  else()
    set(_lock_file "${PROJECT_SOURCE_DIR}/dependencies.lock.json")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_lock_file}")
  file(READ "${_lock_file}" _lock)
  string(JSON _version GET "${_lock}" dependencies OpenMS version)
  string(JSON _revision GET "${_lock}" dependencies OpenMS source_revision)
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OpenMS requires a resolved 40-character source revision")
  endif()
  set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
  set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
  find_package(OpenMSData ${_version} EXACT CONFIG REQUIRED ${ARGN})
  if(NOT OpenMSData_SOURCE_REVISION STREQUAL _revision)
    message(FATAL_ERROR "OpenMS data revision mismatch: expected ${_revision}, got ${OpenMSData_SOURCE_REVISION}")
  endif()
  _openms4_require_clean_sdk(OpenMSData)
  openms4_source_revision(_package_revision _package_dirty)
  get_cmake_property(_variables VARIABLES)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^OpenMS_")
      set(${_variable} "${${_variable}}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

# A combined install prefix is the default deployment layout. Separately installed
# SDKs may be supplied explicitly through CMAKE_INSTALL_RPATH; no producer path leaks.
function(openms4_install_rpath target)
  if(UNIX)
    get_target_property(_type ${target} TYPE)
    get_target_property(_bundle ${target} MACOSX_BUNDLE)
    if(_bundle)
      set(_directory "${CMAKE_INSTALL_BINDIR}/${target}.app/Contents/MacOS")
    elseif(_type STREQUAL "EXECUTABLE")
      set(_directory "${CMAKE_INSTALL_BINDIR}")
    else()
      set(_directory "${CMAKE_INSTALL_LIBDIR}")
    endif()
    file(RELATIVE_PATH _relative "/${_directory}" "/${CMAKE_INSTALL_LIBDIR}")
    if(APPLE)
      set(_origin "@loader_path")
    else()
      set(_origin "$ORIGIN")
    endif()
    set_target_properties(${target} PROPERTIES
      INSTALL_RPATH "${_origin}/${_relative};${CMAKE_INSTALL_RPATH}"
      INSTALL_RPATH_USE_LINK_PATH FALSE)
  endif()
endfunction()

# The same standalone helper verifies the recorded source state before compilation.
if(OPENMS4_CHECK_SOURCE_DIR)
  openms4_source_revision(_current_revision _current_dirty)
  _openms4_dirty_value("${OPENMS4_EXPECTED_DIRTY}" "OPENMS4_EXPECTED_DIRTY" _expected_dirty)
  if(NOT _current_revision STREQUAL OPENMS4_EXPECTED_REVISION OR
     NOT _current_dirty STREQUAL _expected_dirty)
    message(FATAL_ERROR "Package source identity changed after configuration; rerun CMake before building")
  endif()
endif()
